name: pkgx/setup
description: >
  Installs `pkgx` to your GitHub Actions runner.
inputs:
  +:
    description: |
      Whitespace separated, pkgs to supplement the environment. eg.

      ```yaml
      +: deno@1.36 rust@1.60
      ```
    required: false
  PKGX_DIR:
    description: >
      Where pkgs are cached.
      Defaults to `$HOME/.pkgx`.
    required: false
  version:
    description: >
      The version of `pkgx` to install.
      Defaults to ^1.
    required: false
    default: ^1
runs:
  using: node20
  main: dist/out/index.js
