name: tea/setup
description: >
  Installs tea.xyz to your GitHub Actions runner.
inputs:
  target:
    description: >
      The executable markdown target.
    required: false
  prefix:
    description: >
      Where tea installs.
      Set to `null` to install to the tea default (~/.tea).
      For GHA we default to `~/opt`.
    required: false
outputs:
  version:
    description: Your project’s version.
runs:
  using: node16
  main: action.js
