name: tea/setup
description: >
  Installs tea.xyz to your GitHub Actions runner.
inputs:
  prefix:
    description: >
      Where tea installs.
      Set to `null` to install to the tea default (~/.tea).
      For GHA we default to `~/opt`.
    required: false
  version:
    description: >
      The version of teaxyz/cli to install.
      Defaults to the most recent published version.
    required: false
  srcroot:
    description: |
      Override detection of `$SRCROOT`.

      tea normally finds your `$SRCROOT` by looking for a `.git` directory.
      However, if git is not installed the checkout action uses the GitHub
      API to download the repository.

      You will need this if you depend on the virtual environment tea
      provides.
outputs:
  version:
    description: Your project’s version.
runs:
  using: node16
  main: action.js
