name: tea/setup
description: >
  Installs tea.xyz to your GitHub Actions runner.
inputs:
  prefix:
    description: >
      Where tea stows its packages.
      Defaults to `$HOME/.tea`.
    required: false
  version:
    description: >
      The version of teaxyz/cli to install.
      Defaults to the most recent published version.
    required: false
  chaste:
    description: >
      Do not install packages.
      Defaults to `false`.
    default: false
  +:
    description: |
      Whitespace separated, pkgs to supplement the environment. eg.

      ```yaml
      +: |
        deno.land^1.30
        rust-lang.org^1.60
      ```

      By default tea reads your developer environment and adds those packages.
      Specifying additional packages here is a way to augment that.
    required: false
  srcroot:
    description: |
      Override detection of `$SRCROOT`.

      tea normally finds your `$SRCROOT` by looking for a `.git` directory.
      However, if git is not installed the checkout action uses the GitHub
      API to download the repository.

      You will need this if you depend on the virtual environment tea
      provides.
outputs:
  version:
    description: Your project’s version.
runs:
  using: node16
  main: action.js
