name: tea/setup
description: >
  Installs tea.xyz to your GitHub Actions runner.
inputs:
  +:
    description: |
      Whitespace separated, pkgs to supplement the environment. eg.

      ```yaml
      +:
        deno.land@1.30
        rust-lang.org@1.60
      ```

      By default tea reads your developer environment and adds those packages.
      Specifying additional packages here is a way to augment that.
    required: false
  TEA_DIR:
    description: >
      Where pkgs are cached.
      Defaults to `$HOME/.tea`.
    required: false
  version:
    description: >
      The version of teaxyz/cli to install.
      Defaults to the @latest.
    required: false
runs:
  using: node16
  main: dist/out/index.js
