on:
  pull_request:
    paths:
      - pre-reqs.ts
      - .github/workflows/ci-pre-reqs.yml

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-reqs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
        - debian:buster-slim
        - archlinux:latest
        - ubuntu:latest
        - fedora:latest
        # - alpine:latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: sh -x ./pre-reqs.sh
      - run: tea -X node -e 'console.log(1)'
