name: smoke-test

on: [workflow_dispatch]

concurrency:
  group: ${{ github.ref }}/smoke-test
  cancel-in-progress: true

permissions:
  contents: read
  issues: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  notify:
    runs-on: ubuntu-latest
    needs: [ci]
    if: always()
    steps:
      - uses: martialonline/workflow-status@v3
        id: status
      - uses: actions/checkout@v3
        if: ${{ steps.status.outputs.status == 'failure' }}
      - uses: JasonEtco/create-an-issue@v2
        if: ${{ steps.status.outputs.status == 'failure' }}
        with:
          filename: .github/CI_FAILURE_ISSUE_TEMPLATE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
